# Solar Forecast ML Integration - Services
# ✅ Services als Alternative zu UI-Buttons
# Version 4.8.0
# von Zara

install_dependencies:
  name: Abhängigkeiten installieren
  description: >
    Installiert fehlende Python-Abhängigkeiten (numpy, aiofiles) automatisch.
    Nach erfolgreicher Installation ist ein Home Assistant Neustart erforderlich.
  fields: {}

check_dependencies:
  name: Abhängigkeiten prüfen
  description: >
    Prüft den Status aller Python-Abhängigkeiten und zeigt das Ergebnis in einer Notification an.
  fields: {}

force_retrain:
  name: ML-Model neu trainieren
  description: >
    Erzwingt sofortiges Neutraining des Machine Learning Models mit allen verfügbaren Daten.
  fields: {}

reset_model:
  name: ML-Model zurücksetzen
  description: >
    Setzt das ML-Model auf den Werkszustand zurück. ACHTUNG: Löscht alle trainierten Daten!
  fields: {}

clear_history:
  name: Verlauf löschen
  description: >
    Löscht die gesamte Prediction History. ACHTUNG: Nicht rückgängig zu machen!
  fields: {}
